environment:
  nodejs_version: "9"
image: Visual Studio 2013
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - npm run lint
  - npm run test
  - npm run build
build: off
