version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: selenium/standalone-chrome:3.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn examples &
      - run: yarn e2e
